# Generated by Django 6.0 on 2026-01-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_owned_permission', models.BooleanField(default=True)),
                ('read_all_permission', models.BooleanField(default=False)),
                ('create_permission', models.BooleanField(default=False)),
                ('update_owned_permission', models.BooleanField(default=True)),
                ('update_all_permission', models.BooleanField(default=False)),
                ('delete_owned_permission', models.BooleanField(default=True)),
                ('delete_all_permission', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('User', 'User')], max_length=128, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'default_related_name': 'roles',
            },
        ),
    ]
