# Generated by Django 6.0 on 2026-01-04 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('business_objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrule',
            name='business_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='business_objects.businessresource'),
        ),
        migrations.AddField(
            model_name='accessrule',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='access.role'),
        ),
        migrations.AddConstraint(
            model_name='accessrule',
            constraint=models.UniqueConstraint(fields=('role', 'business_resource'), name='unique_role_business_resource'),
        ),
    ]
