# Generated by Django 6.0 on 2026-01-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Admin', 'Администратор'), ('Manager', 'Менеджер'), ('User', 'Пользователь')], max_length=128, unique=True),
        ),
    ]
